[versions]
konsist = "0.17.3"
#kotest = "6.0.5"
#kotest-spring = "6.0.5"
kotest = "5.9.1"
kotest-spring = "1.3.0"
springmockk = "4.0.2"

[libraries]
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref  = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref  = "kotest" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version.ref = "kotest-spring" }
#kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest-spring" }
